server:
  port: 8095

spring:
  application:
    name: payment-event-server

  datasource:
    url: jdbc:postgresql://192.168.117.129:5432/payment-event
    username: user
    password: "000000"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

connector-service:
  payment-event-url: http://localhost:8083/internal/v1/payment-events

simulation:
  fixed-delay-ms: 10000
  data-file: classpath:simulation/payment-simulation-data.json
