apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: payment-api-event-server
  namespace: service
  labels:
    app: payment-api-event-server
spec:
  replicas: 1
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause:
          duration: 30s
      - setWeight: 50
      - pause:
          duration: 30s
  selector:
    matchLabels:
      app: payment-api-event-server
  template:
    metadata:
      labels:
        app: payment-api-event-server
      annotations:
        sidecar.istio.io/proxyCPU: "10m"
    spec:
      containers:
        - name: payment-api-event-server
          image: registry.gitlab.com/5kstration/payment-api-event-server:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: payment-simulation-data
              mountPath: /app/config/payment-simulation-data.json
              subPath: payment-simulation-data.json
              readOnly: true
          envFrom:
            - configMapRef:
                name: payment-api-event-server-config
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-db-secret
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-db-secret
                  key: DB_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 5
          resources:
            requests:
              cpu: "20m"
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      imagePullSecrets:
        - name: gitlab-registry-credentials
      volumes:
        - name: payment-simulation-data
          secret:
            secretName: payment-api-event-server-simulation-secret
