apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: onprem-gateway
  namespace: service
spec:
  selector:
    istio: ingress
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: payment-api-event-server
  namespace: service
spec:
  hosts:
    - "*"
  gateways:
    - onprem-gateway
  http:
    - name: payment-api-event-server-root
      match:
        - uri:
            exact: /payment-api-event-server
      rewrite:
        uri: /
      route:
        - destination:
            host: payment-api-event-server.service.svc.cluster.local
            port:
              number: 8080
    - name: payment-api-event-server-prefix
      match:
        - uri:
            prefix: /payment-api-event-server/
      rewrite:
        uri: /
      route:
        - destination:
            host: payment-api-event-server.service.svc.cluster.local
            port:
              number: 8080
